### PR TITLE
fix: expose instance swagger using virtual service.

### LINKED ISSUE #13: Swagger UI and API not exposed via Virtual Service after Istio updates
**Describe the bug**
The Swagger UI and API are not available after the recent Istio updates.

**Provide Information**
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Output of `helm ls sitewhere`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Minikube`

SiteWhere App Version:
`3.0.1`

SiteWhere Chart Version:

**To Reproduce**
Attempt to access swagger via URL `http://host/swagger`

**Expected behavior**
Swagger UI and API available.

**Additional context**

### PR DESCRIPTION
**Pull request by jorgevillaverde-sitewhere**
Closes: #13

### CODE REVIEW

**Comment by jorgevillaverde-sitewhere** [comment]
For an instance named `sitewhere`, this is the `VirtualSevice` that this fix generates

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  creationTimestamp: "2021-01-24T14:01:14Z"
  generation: 1
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:gateways: {}
        f:hosts: {}
        f:http: {}
      f:status: {}
    manager: swctl
    operation: Update
    time: "2021-01-24T14:01:14Z"
  name: sitewhere-vs
  namespace: sitewhere
  resourceVersion: "3445"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/sitewhere/virtualservices/sitewhere-vs
  uid: 15903d74-cd01-4b3c-9e84-dc08985f5a76
spec:
  gateways:
  - sitewhere-system/sitewhere-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /sitewhere/swagger
    - uri:
        prefix: /sitewhere/swagger/
    name: swagger
    rewrite:
      uri: /swagger
    route:
    - destination:
        host: instance-management.sitewhere.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /sitewhere/openapi
    - uri:
        prefix: /sitewhere/openapi/
    name: openapi
    rewrite:
      uri: /openapi
    route:
    - destination:
        host: instance-management.sitewhere.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /sitewhere
    name: instance-rest
    rewrite:
      uri: /sitewhere
    route:
    - destination:
        host: instance-management.sitewhere.svc.cluster.local
        port:
          number: 8080
```

So, for accessing swagger the URL would be `http://hostname:port/sitewhere/swagger`

We can not use  `http://hostname:port/swagger`, since 3.0 support multiple instances now and we would have one swagger per instance.

**Comment by jorgevillaverde-sitewhere** [comment]
image
The only gotcha is that we would need to explore `/sitewhere/openapi` in order to get the OpenAPI en swagger. By default it goes to `/openapi` and this is the error you'll get.

image

**Comment by jorgevillaverde-sitewhere** [comment]
@derekadams, is you are OK with this, I'll merge the PR and release `swctl` v0.4.3.

**Comment by derekadams** [comment]
Yes, that looks like a good solution. I agree with releasing `swctl` v0.4.3 👍

**Pull request merged**
